### ISSUE TITLE
Mind me copy a bit of your code?

### ISSUE THREAD

**Issue by DKingAlpha** [vinyldarkscratch/lightpad#1]
Hi guys,
Recently I am doing a project on mapping launchpad as a cool game controller device.  C++ on VS, targeting to windows user.
Before reading your codes I has implemented the Launchpad Pro Interface using Windows API part about MIDI (pure winapi without any rtmidi), But I got some trouble while using midifile to map the right note-button until I saw your code. You has done Launchpad S part too and done the right mapping to them while I would like to add more compatibility. And obviously you have a better sense of architecture than me where I can not reach now.
Laterly I will publish my project in github.

After reading your code I am getting down to refactoring with rtmidi. Using different methods to send message is  a PITA.

The reason why I prefer to copy it to my project instead of implementing yours is that our projects vary too much. And I still prefer my coding style in a way so wont really help a lot by commiting to your repo.

Besides the request:
I have seen your pulse and flash are left empty. It's simple sys-ex command with two bytes. Check the guide book.
I create some methods like SendCmdBytes(midiOutLongMsg) , SendSysExCmdBytes(midiOutLongMsg) , SendDWORD(midiOutShortMsg) when I dont know a thing called rtmidi.  And ShowText, SetPadColor , SetColomn/RowColor to get ready for game mapping development. 
Hope these give you some hints.

**Comment by queengooborg** [comment]
Hi there,

I'm having a hard time understanding what you're trying to say.  Can you explain what you mean by "architecture" in this case?

As for pulse and flash (for the Launchpad S), that's correct, I'm not sure how to implement those just yet.  I didn't find anything about them in the documentation for the S (but I did for the Pro), particularly since I'm more focused on the animation side than the hardware compatibility to begin.  But, it's not out of my plans, and I'll start working on it as soon as I can.  ;)

Good luck on your game!  Feel free to use any code from here as long as you put our name in the credits and link back to us.  :)

**Comment by DKingAlpha** [comment]
I mean structure, it's a language problem , sorry.
I have done porting your code. ETA 2days then I will put it in github.
