### ISSUE TITLE
displayText error

### ISSUE THREAD

**Issue by DKingAlpha** [vinyldarkscratch/lightpad#3]
Hi it's a complex to send another PR so I will report problem here since now.

1.
displayText error
it should be 
```
	message.push_back(240);
	message.push_back(0);
	message.push_back(32);
	message.push_back(41);
	message.push_back(2);
	message.push_back(16);
	message.push_back(20);    // you wrote 40
	message.push_back(color);
	message.push_back(loop); 
	message.push_back(speed);
        // push text
```

2. Mutex
mutex should be added to prevent bad bytes sequence when multithreads are called.
I have seen that caused trouble.

3.(recommend)Make message as function temp var
Maing message class member might have message bad content if forget to clean it.

Following up.

**Comment by queengooborg** [comment]
Hey again, you're right, I _did_ type 40 instead of 20, whoops!  Thank you for the catch, just fixed and pushing now.  ;)  I'm also thinking about changing the interface to allow for changing text speed mid-string, so it would be something like "/1This is /7awesome!  /4I never programmed//used this /5text feature before!" where the forward slash is the escape character (or some other symbol).

As for utilizing mutex, I definitely have plans for implementing it in the future.  In the program's current state, I don't feel that it's ready for incorporating multithreading quite yet, as we're still working on loading, playing, and writing animations.  (Make it work, make it work right, make it work efficiently, then make it work while looking fancy, that's my pattern.  :P)  Plus, I still need to track down and eliminate the thousands of memory leaks in the code... XD
<img width="2032" alt="screen_shot_2017-03-10_at_12 33 12" src="https://cloud.githubusercontent.com/assets/5179191/23813412/a0183982-0593-11e7-816f-7f23db6e371a.png">

And finally, for making the message variable a local function variable, honestly I find that to have more downsides than benefits -- it means creating a new variable every time you want to send a message to the Launchpad, which means responsibility to deallocate it once you're done.  Instead, I added an overload to sendMessage(), where passing no arguments will flush the content in the message vector.  That also removes the need to copy and paste the lines of code for flushing, like I had done before.  X3

**Comment by DKingAlpha** [comment]
I am coding my project at local 06:00 in the morning, overnight. Gonna finish that O(∩_∩)O.

If the expense of vector is a trouble for you , I have to stop you reading my code XD.
You need to know that I was a guy who would use char* instead of string all the time, even I had to invent wheels again and again.
But to make that LpdGamer reliable and made less subtle mistake in case when I cant find bugs later, I never worry expenses in that project. Who can run Ableton Live will also run that thing. I am not writing a kernel any way. 

Back to Lightpad.
I remember that vectors will deconstruct themselves when the function they are in returns. Except malloc/new.
and i heard that vector.clear() will not destroy it's elements memory but lightpad or lpdgamer is not frequently reloading a vector, I think that's acceptable.
I also checked through rtmidi and midifile source code , they use lots of clear() too. And I noticed that they use it like vector.erase(remove_if(begin(),end())) for once.

I had a bad sense about mem leakage in lpdgamer.... checking that later.

**Comment by queengooborg** [comment]
I never said that using vectors is troublesome, though, I'm talking about recreating vectors for every function call, then worrying about sending their contents and deallocating them again after we're finished.  Currently, I'm worrying about eliminating memory leaks instead of opening possibilities for new ones, as well as opening up for more possible code inconsistency.  Even if they deconstruct themselves after the function finishes, there's still the fact that we'd be repeating lines of code over and over again, when we really don't need to.

As for RtMidi and MidiFile, I actually hadn't looked into their sources, but I hadn't heard about [vector::clear](http://www.cplusplus.com/reference/vector/vector/clear/) until you mentioned it just now -- I only knew about [vector::erase](http://www.cplusplus.com/reference/vector/vector/erase/).  Actually, the site I linked states that vector::clear "removes all elements from the vector (which are destroyed), leaving the container with a size of 0," definitely much shorter than `message.erase(message.begin(), message.begin() + message.size());` and, by the looks of it, has the same result.  I'll have to look into that more and double-check to confirm before I start using it.  X3
